pipeline:
    build:
      group: test-thirdeye-build
      image: plugins/docker
      registry: c.rzp.io
      repo: c.rzp.io/razorpay/thirdeye
      dockerfile: Dockerfile.thirdeye
      build_args:
        - GIT_COMMIT_HASH=${DRONE_COMMIT_SHA}
        - GIT_TOKEN
      secrets:
        - source: harbor_docker_username
          target: docker_username
        - source: harbor_docker_password
          target: docker_password
        - source: git_token
          target: GIT_TOKEN
      tags: ${DRONE_COMMIT_SHA}
      when:
        status: [success]
        event:
          exclude: [deployment, pull_request, tag]
          include: [push]