language: java

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

matrix:
  exclude:
    - jdk: openjdk7
      env: RUN_INTEGRATION_TESTS=false
    - jdk: oraclejdk8
      env: RUN_INTEGRATION_TESTS=false

cache:
  directories:
    - $HOME/.m2
  yarn: true

dist: precise
sudo: false

addons:
  chrome: stable

before_install: 
  - nvm install 6 CC=clang CXX=clang++
  - npm config set spin false
  - npm install -g npm@4
  - npm --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g bower

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master
