language: java

env:
  - RUN_INTEGRATION_TESTS=true
  - RUN_INTEGRATION_TESTS=false

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

matrix:
  exclude:
    - jdk: openjdk7
      env: RUN_INTEGRATION_TESTS=false
    - jdk: oraclejdk8
      env: RUN_INTEGRATION_TESTS=false

cache:
  directories:
    - $HOME/.m2

dist: precise
sudo: false

addons:
  chrome: stable

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh
  - ./thirdeye/thirdeye-frontend/node_modules/.bin/ember test --silent --skip-cleanup

branches:
  only:
    - master
