language: java
sudo: false
dist: trusty

before_install:
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
  yarn: true

addons:
  firefox: latest

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

branches:
  only:
    - master

jobs:
  include:
    - name: "Integration Tests - OracleJDK 8"
      jdk: oraclejdk8
      env:
        - TEST_CATEGORY=INTEGRATION_TEST
        - KAFKA_VERSION=2.0
    - name: "Unit Tests - OracleJDK 8"
      jdk: oraclejdk8
      env:
        - TEST_CATEGORY=UNIT_TEST
        - KAFKA_VERSION=2.0
    - jdk: oraclejdk8
      env:
        - TEST_CATEGORY=QUICKSTART
        - KAFKA_VERSION=2.0
    - jdk: oraclejdk11
      env:
        - TEST_CATEGORY=QUICKSTART
        - KAFKA_VERSION=2.0
    - jdk: openjdk8
      env:
        - TEST_CATEGORY=QUICKSTART
        - KAFKA_VERSION=2.0
    - jdk: openjdk11
      env:
        - TEST_CATEGORY=QUICKSTART
        - KAFKA_VERSION=2.0