language: java
sudo: false
dist: trusty

before_install:
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
  yarn: true

addons:
  firefox: latest

install:
  - ./.travis_install.sh

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
        - name: "Integration Tests - OracleJDK 8"
          jdk: oraclejdk8
          script:
            - ./.travis_test.sh
          env:
            - RUN_INTEGRATION_TESTS=true
        - name: "Unit Tests - OracleJDK 8"
          jdk: oraclejdk8
          script:
            - ./.travis_test.sh
          env:
            - RUN_INTEGRATION_TESTS=false
        - name: "QuickStart - OracleJDK 8"
          jdk: oraclejdk8
          script:
            - ./.travis_quickstart.sh
        - name: "QuickStart - OracleJDK 11"
          jdk: oraclejdk11
          script:
            - ./.travis_quickstart.sh
        - name: "QuickStart - OpenJDK 8"
          jdk: openjdk8
          script:
            - ./.travis_quickstart.sh
        - name: "QuickStart - OpenJDK 11"
          jdk: openjdk11
          script:
            - ./.travis_quickstart.sh
    - stage: Deploy
      script:
        - mvn clean deploy -s .ci.settings.xml -Drevision=0.2.$TRAVIS_BUILD_NUMBER
