language: java
sudo: false
dist: trusty
before_install:
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
  && chmod +x ~/bin/jq
- export PATH=$PATH:~/bin
- jq --version
- export REVISION="-dev-${TRAVIS_BUILD_NUMBER}"
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  yarn: true
addons:
  firefox: latest
install:
- "./.travis_install.sh"
script:
- "./.travis_nightly_build.sh"
env:
  global:
  - secure: jUmGgAtizTZD5hVeBKbejCMIbyUX7XrmB2ZX5MUkFZtUNqtVZ3TdVgo8n3ndba4qq5JZ5EzACZTeNOqnWaIghcj9KzlX8xr1e7JvcmIef/2RKljq7Klxr6mh2oC3YyIoIbK5H57VpFuxcItUNo1LGTNJytomibPvPoGAuLRnH1meFhkMxZWvLMw0nv7IGxvnMh3n7FcRD0nH0zfipgwGTXS8IwblTag9hzLzyFaxsEZL0sa5UX02uwfaisJuzEknDf0BlDfsfGkfYKrubfVawM5lUxLaStr0Ljx7Cfys8oJURoUNDjKrTQbyYYCSuO3KzKcEEqCw4baLIi0hPDZ4qEYpt8NOzAD320uzONxzEatx01c3B2TRiDhFJau/1XUH8uy7xu0nru7EXckmzq51QByzGx7dh81ANcwvxxNSTchFyP9PReGPQaC5Q/xizfpbD+2WRJSYQThrceDyEVE1MVASRB3+Ra6IJvmgEOwXDcUdsvg6HpQ1zxgUvWYmxEKrAZX6/73Me6WOcJ3j7BUym8DfuEK1K+1TeU82gzvdMqth9ed8FjGZjlBO9BFEdtRhrgqI/GmbSqKhK6GBcSAA3WFONMxzT44QJomk1+nOj4Y5RyhR+hrTBIiNQ9boJgsvTWOo+zKwinqiZrw2N0feO0S/CI7Zgzm0aYQEsgMelwI=
  - secure: U6eoWopE3P8vkC2Fwh5ux+Hdgs5ULOh0PxkgUc40ix3pE2lJEoXKxPMLELa4xSdqnTLWCU2s9Sb7kxh5WY5127ijCNFN2jvSDhq5MHWnAOFqa+OEol8mg/tzcRnAebkgZBK/Br+t0YLJZ7Rov4S1d+z4NXL5PMn/SDPQlnINHVbxR9eIhopLUnxJS8wUqSwPLRFB3uTBFea5vdwbDT+XbaWXrSK7U0CWdxLkhtESk6OO4MhlUehe32+QAxTMcnGuFo68AVqbDRPA+7dg0F26mD+CCY0SNY+idPN0czblnTPOt5CylQYzsqpmTvSp+3/BpGjwv5uY+5gZBD+aO39GYv6taIl+10gnHBUO88bBP0Zw7ys5OblpIT/KrB5yIeS0UwOUFJogTztcn2H6r9SSxUE8FsPMAJgCbMrHCC2fsP8a459UZukhcFIrnOlMFM4SARu88MIrbkCWevPMbetp2hYaOmAoY8aefwG0INSNxGgTI3+PBQ1Rre8/k7M8VEJYcRxEMm37KDhvcF0m16CwxxkTxavQDOMjoGlj9dPz25W1ody0cF3ss2wqAZvSb92XEvBwCoy2NeR4LNr5C7y+8Xbb9ooB6C4Kef4QDjDvK+EhVdCszQ+vadkoi+k79jvWbXcaQpOBeYZd/sTPmLyC0p3qHp6mLHO2R2ZyfU6mQIg=
