language: java

env:
  - PINOT_MODULE="pinot-integration-tests"
  - PINOT_MODULE="pinot-core"
  - PINOT_MODULE="pinot-controller"
  - PINOT_MODULE="pinot-api"
  - PINOT_MODULE="pinot-common"
  - PINOT_MODULE="pinot-transport"
  - PINOT_MODULE="pinot-broker"
  - PINOT_MODULE="pinot-server"
  - PINOT_MODULE="pinot-perf"

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  - ./.travis_install.sh

script:
  - ./.travis_test.sh

after_success:
  - bash <(cat .codecov_bash)

branches:
  only:
    - master
