version: '3'
services:
  thirdeye_mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: thirdeye
      MYSQL_PASSWORD: thirdeye
    volumes:
      - ./thirdeye/thirdeye-pinot/config-templates/dev/create-schema.sql:/docker-entrypoint-initdb.d/init.sql
  thirdeye_frontend:
    image: razorpay/thirdeye
    volumes:
      - ./thirdeye/thirdeye-pinot/config-templates/cloud/persistence.yml.tmpl:/opt/thirdeye/config/default/persistence.yml.tmpl
      - ./thirdeye/thirdeye-pinot/config-templates/cloud/data-sources/data-sources-config.yml.tmpl:/opt/thirdeye/config/default/data-sources/data-sources-config.yml.tmpl
        #- ./thirdeye/thirdeye-pinot/config-templates/dev/persistence.yml:/opt/thirdeye/config/default/persistence.yml
        #- ./thirdeye/thirdeye-pinot/config-templates/dev/data-sources/data-sources-config.yml:/opt/thirdeye/config/default/data-sources/data-sources-config.yml
      - ./dockerconf/entrypoint_dev.sh:/opt/thirdeye/bin/entrypoint_dev.sh
      - ./dockerconf/entrypoint.sh:/opt/thirdeye/bin/entrypoint.sh
    environment:
      CONFIG_DIR: /opt/thirdeye/config/default
      POSTGRES_HOSTNAME: localhost
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: thirdeye
      POSTGRESQL_PASSWORD: root
      MYSQL_HOSTNAME: thirdeye_mysql
      MYSQL_PORT: 3306
      THIRDEYE_DATABASE: thirdeye
      MYSQL_PASSWORD: root
    ports:
      - 1426:1426
      - 1427:1427
        #entrypoint: ["/bin/sh", "/opt/thirdeye/bin/entrypoint_dev.sh", "frontend"]
    entrypoint: ["/bin/sh", "/opt/thirdeye/bin/entrypoint.sh", "frontend"]
    depends_on:
      - thirdeye_mysql
    links:
      - thirdeye_mysql
  thirdeye_backend:
    image: razorpay/thirdeye
    volumes:
      - ./thirdeye/thirdeye-pinot/config-templates/cloud/persistence.yml.tmpl:/opt/thirdeye/config/default/persistence.yml.tmpl
      - ./thirdeye/thirdeye-pinot/config-templates/cloud/data-sources/data-sources-config.yml.tmpl:/opt/thirdeye/config/default/data-sources/data-sources-config.yml.tmpl
        #- ./thirdeye/thirdeye-pinot/config-templates/dev/persistence.yml:/opt/thirdeye/config/default/persistence.yml
        #- ./thirdeye/thirdeye-pinot/config-templates/dev/data-sources/data-sources-config.yml:/opt/thirdeye/config/default/data-sources/data-sources-config.yml
      - ./dockerconf/entrypoint_dev.sh:/opt/thirdeye/bin/entrypoint_dev.sh
      - ./dockerconf/entrypoint.sh:/opt/thirdeye/bin/entrypoint.sh
    environment:
      CONFIG_DIR: /opt/thirdeye/config/default
      POSTGRES_HOSTNAME: localhost
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: thirdeye
      POSTGRESQL_PASSWORD: root
      MYSQL_HOSTNAME: thirdeye_mysql
      MYSQL_PORT: 3306
      THIRDEYE_DATABASE: thirdeye
      MYSQL_PASSWORD: root
      #entrypoint: ["/bin/sh", "/opt/thirdeye/bin/entrypoint_dev.sh", "backend"]
    entrypoint: ["/bin/sh", "/opt/thirdeye/bin/entrypoint.sh", "backend"]
    depends_on:
      - thirdeye_mysql
    links:
      - thirdeye_mysql
