apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  pinot-server.conf: |-
    pinot.server.netty.port={{ .Values.server.ports.netty }}
    pinot.server.adminapi.port={{ .Values.server.ports.admin }}
    pinot.server.instance.dataDir={{ .Values.server.dataDir }}
    pinot.server.instance.segmentTarDir={{ .Values.server.segmentTarDir }}
    pinot.set.instance.id.to.hostname=true
