# Default values for Pinot.

image:
  repository: winedepot/pinot
  tag: 0.1.13-SNAPSHOT
  pullPolicy: IfNotPresent

namespace: pinot-quickstart

cluster:
  name: pinot-quickstart
  zookeeper: zookeeper:2181/pinot

controller:
  name: controller

  replicaCount: 1

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10G
    #storageClass: "ssd"

  data:
    dir: /var/pinot/controller/data

  port: 9000

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 9000
    nodePort: ""

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

broker:
  name: broker

  replicaCount: 1

  port: 8099
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8099
    nodePort: ""

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

server:
  name: server

  replicaCount: 1

  ports:
    netty: 8098
    admin: 8097

  dataDir: /var/pinot/server/data/index
  segmentTarDir: /var/pinot/server/data/index

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10G
    #storageClass: "ssd"

  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8098
    nodePort: ""

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podAnnotations: {}

  updateStrategy:
    type: RollingUpdate

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------

# zkHosts: pinot-zookeeper-headless:2181

zookeeper:
  enabled: true
  ## Environmental variables to set in Zookeeper
  ##
  env:
    ## The JVM heap size to allocate to Zookeeper
    ZK_HEAP_SIZE: "512M"
  ## Configure Zookeeper persistence
  persistence:
    enabled: true
