apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: pinot-quickstart
spec:
  ports:
  - name: zookeeper
    port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: pinot-quickstart
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zookeeper
          image: solsson/kafka:2.1.0@sha256:ac3f06d87d45c7be727863f31e79fbfdcb9c610b51ba9cf03c75a95d602f15e1
          env:
            - name: JMX_PORT
              value: "5555"
          ports:
            - name: zookeeper
              containerPort: 2181
            - name: jmx
              containerPort: 5555
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /tmp/zookeeper
          command:
            - ./bin/zookeeper-server-start.sh
            - config/zookeeper.properties
          readinessProbe:
            tcpSocket:
              port: 2181
            timeoutSeconds: 1
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "zookeeper"
      resources:
        requests:
          storage: 10G
