apiVersion: v1
entries:
  pinot:
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2020-05-04T00:59:04.094942-07:00"
    dependencies:
    - condition: pinot.zookeeper.enabled,zookeeper.enabled
      name: zookeeper
      repository: https://kubernetes-charts-incubator.storage.googleapis.com/
      version: 2.1.3
    description: Apache Pinot is a realtime distributed OLAP datastore, which is used
      to deliver scalable real time analytics with low latency. It can ingest data
      from offline data sources (such as Hadoop and flat files) as well as online
      sources (such as Kafka). Pinot is designed to scale horizontally.
    digest: e2b52aff7c2bae33ea0bbc9335b94d218a94afc56a11388f1848d4726c0e8221
    home: https://pinot.apache.org/
    keywords:
    - olap
    - analytics
    - database
    - pinot
    maintainers:
    - email: dev@pinot.apache.org
      name: pinot-dev
    name: pinot
    sources:
    - https://github.com/apache/incubator-pinot
    urls:
    - pinot-0.2.0.tgz
    version: 0.2.0
  zookeeper:
  - apiVersion: v1
    appVersion: 3.5.5
    created: "2020-05-04T00:59:04.096461-07:00"
    description: Centralized service for maintaining configuration information, naming,
      providing distributed synchronization, and providing group services.
    digest: ce79cf63a1284c16e6b615a3dea62e619ce99dea85419be5b46a8ee6ceec3b4e
    home: https://zookeeper.apache.org/
    icon: https://zookeeper.apache.org/images/zookeeper_small.gif
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lachlan.evenson@microsoft.com
      name: lachie83
    - email: owensk@google.com
      name: kow3ns
    name: zookeeper
    sources:
    - https://github.com/apache/zookeeper
    - https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper
    urls:
    - charts/zookeeper-2.1.3.tgz
    version: 2.1.3
generated: "2020-05-04T00:59:04.087389-07:00"
