name: Cancelling Duplicates
on:
  workflow_run:
    workflows: 
      - 'Pinot Tests'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout potiuk/cancel-workflow-runs
        with:
          repository: potiuk/cancel-workflow-runs
          path: ./build/.actions/potiuk/cancel-workflow-runs
          ref: 953e057dc81d3458935a18d1184c386b0f6b5738 # @master
          fetch-depth: 1
      - uses: ./build/.actions/potiuk/cancel-workflow-runs
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
